matrix:
  include:
    - language: elixir
      elixir:
        - '1.7.4'
      before_install: cd back-end

    - language: node_js
      node_js:
        - "node"
      before_install: cd front-end
      cache: npm
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master
